"""add product position

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 20:35:54.688372

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("position", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_index(op.f("ix_products_position"), "products", ["position"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_position"), table_name="products")
    op.drop_column("products", "position")
    # ### end Alembic commands ###
