"""add chat usage

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 09:27:54.847284

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("tool_rounds", sa.SmallInteger(), nullable=False),
        sa.Column("outcome", sa.String(length=12), nullable=False),
        sa.Column("provider_request_id", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_usage_client_hash"), "chat_usage", ["client_hash"], unique=False)
    op.create_index(op.f("ix_chat_usage_created_at"), "chat_usage", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_usage_created_at"), table_name="chat_usage")
    op.drop_index(op.f("ix_chat_usage_client_hash"), table_name="chat_usage")
    op.drop_table("chat_usage")
    # ### end Alembic commands ###
